/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'NIOS_CPU' in SOPC Builder design 'NiosII_Processor'
 * SOPC Builder design path: ../../qsys/NiosII_Processor.sopcinfo
 *
 * Generated: Tue Dec 08 15:15:54 CET 2020
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * BTN_CH_ONOFF configuration
 *
 */

#define ALT_MODULE_CLASS_BTN_CH_ONOFF altera_avalon_pio
#define BTN_CH_ONOFF_BASE 0x8080
#define BTN_CH_ONOFF_BIT_CLEARING_EDGE_REGISTER 0
#define BTN_CH_ONOFF_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BTN_CH_ONOFF_CAPTURE 1
#define BTN_CH_ONOFF_DATA_WIDTH 2
#define BTN_CH_ONOFF_DO_TEST_BENCH_WIRING 0
#define BTN_CH_ONOFF_DRIVEN_SIM_VALUE 0
#define BTN_CH_ONOFF_EDGE_TYPE "FALLING"
#define BTN_CH_ONOFF_FREQ 100000000
#define BTN_CH_ONOFF_HAS_IN 1
#define BTN_CH_ONOFF_HAS_OUT 0
#define BTN_CH_ONOFF_HAS_TRI 0
#define BTN_CH_ONOFF_IRQ 5
#define BTN_CH_ONOFF_IRQ_INTERRUPT_CONTROLLER_ID 0
#define BTN_CH_ONOFF_IRQ_TYPE "EDGE"
#define BTN_CH_ONOFF_NAME "/dev/BTN_CH_ONOFF"
#define BTN_CH_ONOFF_RESET_VALUE 0
#define BTN_CH_ONOFF_SPAN 16
#define BTN_CH_ONOFF_TYPE "altera_avalon_pio"


/*
 * BTN_DISPLAY configuration
 *
 */

#define ALT_MODULE_CLASS_BTN_DISPLAY altera_avalon_pio
#define BTN_DISPLAY_BASE 0x80a0
#define BTN_DISPLAY_BIT_CLEARING_EDGE_REGISTER 0
#define BTN_DISPLAY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BTN_DISPLAY_CAPTURE 1
#define BTN_DISPLAY_DATA_WIDTH 6
#define BTN_DISPLAY_DO_TEST_BENCH_WIRING 0
#define BTN_DISPLAY_DRIVEN_SIM_VALUE 0
#define BTN_DISPLAY_EDGE_TYPE "FALLING"
#define BTN_DISPLAY_FREQ 100000000
#define BTN_DISPLAY_HAS_IN 1
#define BTN_DISPLAY_HAS_OUT 0
#define BTN_DISPLAY_HAS_TRI 0
#define BTN_DISPLAY_IRQ 3
#define BTN_DISPLAY_IRQ_INTERRUPT_CONTROLLER_ID 0
#define BTN_DISPLAY_IRQ_TYPE "EDGE"
#define BTN_DISPLAY_NAME "/dev/BTN_DISPLAY"
#define BTN_DISPLAY_RESET_VALUE 0
#define BTN_DISPLAY_SPAN 16
#define BTN_DISPLAY_TYPE "altera_avalon_pio"


/*
 * BTN_ENCODER configuration
 *
 */

#define ALT_MODULE_CLASS_BTN_ENCODER altera_avalon_pio
#define BTN_ENCODER_BASE 0x8090
#define BTN_ENCODER_BIT_CLEARING_EDGE_REGISTER 0
#define BTN_ENCODER_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BTN_ENCODER_CAPTURE 1
#define BTN_ENCODER_DATA_WIDTH 5
#define BTN_ENCODER_DO_TEST_BENCH_WIRING 0
#define BTN_ENCODER_DRIVEN_SIM_VALUE 0
#define BTN_ENCODER_EDGE_TYPE "FALLING"
#define BTN_ENCODER_FREQ 100000000
#define BTN_ENCODER_HAS_IN 1
#define BTN_ENCODER_HAS_OUT 0
#define BTN_ENCODER_HAS_TRI 0
#define BTN_ENCODER_IRQ 4
#define BTN_ENCODER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define BTN_ENCODER_IRQ_TYPE "EDGE"
#define BTN_ENCODER_NAME "/dev/BTN_ENCODER"
#define BTN_ENCODER_RESET_VALUE 0
#define BTN_ENCODER_SPAN 16
#define BTN_ENCODER_TYPE "altera_avalon_pio"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00088820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 100000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x14
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00040020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 100000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x14
#define ALT_CPU_NAME "NIOS_CPU"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00040000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00088820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 100000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x14
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00040020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x14
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00040000


/*
 * DDS0_AM_ModIndex configuration
 *
 */

#define ALT_MODULE_CLASS_DDS0_AM_ModIndex altera_avalon_pio
#define DDS0_AM_MODINDEX_BASE 0x8210
#define DDS0_AM_MODINDEX_BIT_CLEARING_EDGE_REGISTER 0
#define DDS0_AM_MODINDEX_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS0_AM_MODINDEX_CAPTURE 0
#define DDS0_AM_MODINDEX_DATA_WIDTH 32
#define DDS0_AM_MODINDEX_DO_TEST_BENCH_WIRING 0
#define DDS0_AM_MODINDEX_DRIVEN_SIM_VALUE 0
#define DDS0_AM_MODINDEX_EDGE_TYPE "NONE"
#define DDS0_AM_MODINDEX_FREQ 100000000
#define DDS0_AM_MODINDEX_HAS_IN 0
#define DDS0_AM_MODINDEX_HAS_OUT 1
#define DDS0_AM_MODINDEX_HAS_TRI 0
#define DDS0_AM_MODINDEX_IRQ -1
#define DDS0_AM_MODINDEX_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS0_AM_MODINDEX_IRQ_TYPE "NONE"
#define DDS0_AM_MODINDEX_NAME "/dev/DDS0_AM_ModIndex"
#define DDS0_AM_MODINDEX_RESET_VALUE 0
#define DDS0_AM_MODINDEX_SPAN 16
#define DDS0_AM_MODINDEX_TYPE "altera_avalon_pio"


/*
 * DDS0_AM_ModPhaseStep configuration
 *
 */

#define ALT_MODULE_CLASS_DDS0_AM_ModPhaseStep altera_avalon_pio
#define DDS0_AM_MODPHASESTEP_BASE 0x81f0
#define DDS0_AM_MODPHASESTEP_BIT_CLEARING_EDGE_REGISTER 0
#define DDS0_AM_MODPHASESTEP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS0_AM_MODPHASESTEP_CAPTURE 0
#define DDS0_AM_MODPHASESTEP_DATA_WIDTH 32
#define DDS0_AM_MODPHASESTEP_DO_TEST_BENCH_WIRING 0
#define DDS0_AM_MODPHASESTEP_DRIVEN_SIM_VALUE 0
#define DDS0_AM_MODPHASESTEP_EDGE_TYPE "NONE"
#define DDS0_AM_MODPHASESTEP_FREQ 100000000
#define DDS0_AM_MODPHASESTEP_HAS_IN 0
#define DDS0_AM_MODPHASESTEP_HAS_OUT 1
#define DDS0_AM_MODPHASESTEP_HAS_TRI 0
#define DDS0_AM_MODPHASESTEP_IRQ -1
#define DDS0_AM_MODPHASESTEP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS0_AM_MODPHASESTEP_IRQ_TYPE "NONE"
#define DDS0_AM_MODPHASESTEP_NAME "/dev/DDS0_AM_ModPhaseStep"
#define DDS0_AM_MODPHASESTEP_RESET_VALUE 0
#define DDS0_AM_MODPHASESTEP_SPAN 16
#define DDS0_AM_MODPHASESTEP_TYPE "altera_avalon_pio"


/*
 * DDS0_FM_ModDeviationPhase configuration
 *
 */

#define ALT_MODULE_CLASS_DDS0_FM_ModDeviationPhase altera_avalon_pio
#define DDS0_FM_MODDEVIATIONPHASE_BASE 0x81d0
#define DDS0_FM_MODDEVIATIONPHASE_BIT_CLEARING_EDGE_REGISTER 0
#define DDS0_FM_MODDEVIATIONPHASE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS0_FM_MODDEVIATIONPHASE_CAPTURE 0
#define DDS0_FM_MODDEVIATIONPHASE_DATA_WIDTH 32
#define DDS0_FM_MODDEVIATIONPHASE_DO_TEST_BENCH_WIRING 0
#define DDS0_FM_MODDEVIATIONPHASE_DRIVEN_SIM_VALUE 0
#define DDS0_FM_MODDEVIATIONPHASE_EDGE_TYPE "NONE"
#define DDS0_FM_MODDEVIATIONPHASE_FREQ 100000000
#define DDS0_FM_MODDEVIATIONPHASE_HAS_IN 0
#define DDS0_FM_MODDEVIATIONPHASE_HAS_OUT 1
#define DDS0_FM_MODDEVIATIONPHASE_HAS_TRI 0
#define DDS0_FM_MODDEVIATIONPHASE_IRQ -1
#define DDS0_FM_MODDEVIATIONPHASE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS0_FM_MODDEVIATIONPHASE_IRQ_TYPE "NONE"
#define DDS0_FM_MODDEVIATIONPHASE_NAME "/dev/DDS0_FM_ModDeviationPhase"
#define DDS0_FM_MODDEVIATIONPHASE_RESET_VALUE 0
#define DDS0_FM_MODDEVIATIONPHASE_SPAN 16
#define DDS0_FM_MODDEVIATIONPHASE_TYPE "altera_avalon_pio"


/*
 * DDS0_FM_ModPhaseStep configuration
 *
 */

#define ALT_MODULE_CLASS_DDS0_FM_ModPhaseStep altera_avalon_pio
#define DDS0_FM_MODPHASESTEP_BASE 0x81b0
#define DDS0_FM_MODPHASESTEP_BIT_CLEARING_EDGE_REGISTER 0
#define DDS0_FM_MODPHASESTEP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS0_FM_MODPHASESTEP_CAPTURE 0
#define DDS0_FM_MODPHASESTEP_DATA_WIDTH 32
#define DDS0_FM_MODPHASESTEP_DO_TEST_BENCH_WIRING 0
#define DDS0_FM_MODPHASESTEP_DRIVEN_SIM_VALUE 0
#define DDS0_FM_MODPHASESTEP_EDGE_TYPE "NONE"
#define DDS0_FM_MODPHASESTEP_FREQ 100000000
#define DDS0_FM_MODPHASESTEP_HAS_IN 0
#define DDS0_FM_MODPHASESTEP_HAS_OUT 1
#define DDS0_FM_MODPHASESTEP_HAS_TRI 0
#define DDS0_FM_MODPHASESTEP_IRQ -1
#define DDS0_FM_MODPHASESTEP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS0_FM_MODPHASESTEP_IRQ_TYPE "NONE"
#define DDS0_FM_MODPHASESTEP_NAME "/dev/DDS0_FM_ModPhaseStep"
#define DDS0_FM_MODPHASESTEP_RESET_VALUE 0
#define DDS0_FM_MODPHASESTEP_SPAN 16
#define DDS0_FM_MODPHASESTEP_TYPE "altera_avalon_pio"


/*
 * DDS0_OutputRelay configuration
 *
 */

#define ALT_MODULE_CLASS_DDS0_OutputRelay altera_avalon_pio
#define DDS0_OUTPUTRELAY_BASE 0x8190
#define DDS0_OUTPUTRELAY_BIT_CLEARING_EDGE_REGISTER 0
#define DDS0_OUTPUTRELAY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS0_OUTPUTRELAY_CAPTURE 0
#define DDS0_OUTPUTRELAY_DATA_WIDTH 1
#define DDS0_OUTPUTRELAY_DO_TEST_BENCH_WIRING 0
#define DDS0_OUTPUTRELAY_DRIVEN_SIM_VALUE 0
#define DDS0_OUTPUTRELAY_EDGE_TYPE "NONE"
#define DDS0_OUTPUTRELAY_FREQ 100000000
#define DDS0_OUTPUTRELAY_HAS_IN 0
#define DDS0_OUTPUTRELAY_HAS_OUT 1
#define DDS0_OUTPUTRELAY_HAS_TRI 0
#define DDS0_OUTPUTRELAY_IRQ -1
#define DDS0_OUTPUTRELAY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS0_OUTPUTRELAY_IRQ_TYPE "NONE"
#define DDS0_OUTPUTRELAY_NAME "/dev/DDS0_OutputRelay"
#define DDS0_OUTPUTRELAY_RESET_VALUE 0
#define DDS0_OUTPUTRELAY_SPAN 16
#define DDS0_OUTPUTRELAY_TYPE "altera_avalon_pio"


/*
 * DDS0_PM_ModIndex configuration
 *
 */

#define ALT_MODULE_CLASS_DDS0_PM_ModIndex altera_avalon_pio
#define DDS0_PM_MODINDEX_BASE 0x8170
#define DDS0_PM_MODINDEX_BIT_CLEARING_EDGE_REGISTER 0
#define DDS0_PM_MODINDEX_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS0_PM_MODINDEX_CAPTURE 0
#define DDS0_PM_MODINDEX_DATA_WIDTH 32
#define DDS0_PM_MODINDEX_DO_TEST_BENCH_WIRING 0
#define DDS0_PM_MODINDEX_DRIVEN_SIM_VALUE 0
#define DDS0_PM_MODINDEX_EDGE_TYPE "NONE"
#define DDS0_PM_MODINDEX_FREQ 100000000
#define DDS0_PM_MODINDEX_HAS_IN 0
#define DDS0_PM_MODINDEX_HAS_OUT 1
#define DDS0_PM_MODINDEX_HAS_TRI 0
#define DDS0_PM_MODINDEX_IRQ -1
#define DDS0_PM_MODINDEX_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS0_PM_MODINDEX_IRQ_TYPE "NONE"
#define DDS0_PM_MODINDEX_NAME "/dev/DDS0_PM_ModIndex"
#define DDS0_PM_MODINDEX_RESET_VALUE 0
#define DDS0_PM_MODINDEX_SPAN 16
#define DDS0_PM_MODINDEX_TYPE "altera_avalon_pio"


/*
 * DDS0_PM_ModPhaseStep configuration
 *
 */

#define ALT_MODULE_CLASS_DDS0_PM_ModPhaseStep altera_avalon_pio
#define DDS0_PM_MODPHASESTEP_BASE 0x8150
#define DDS0_PM_MODPHASESTEP_BIT_CLEARING_EDGE_REGISTER 0
#define DDS0_PM_MODPHASESTEP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS0_PM_MODPHASESTEP_CAPTURE 0
#define DDS0_PM_MODPHASESTEP_DATA_WIDTH 32
#define DDS0_PM_MODPHASESTEP_DO_TEST_BENCH_WIRING 0
#define DDS0_PM_MODPHASESTEP_DRIVEN_SIM_VALUE 0
#define DDS0_PM_MODPHASESTEP_EDGE_TYPE "NONE"
#define DDS0_PM_MODPHASESTEP_FREQ 100000000
#define DDS0_PM_MODPHASESTEP_HAS_IN 0
#define DDS0_PM_MODPHASESTEP_HAS_OUT 1
#define DDS0_PM_MODPHASESTEP_HAS_TRI 0
#define DDS0_PM_MODPHASESTEP_IRQ -1
#define DDS0_PM_MODPHASESTEP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS0_PM_MODPHASESTEP_IRQ_TYPE "NONE"
#define DDS0_PM_MODPHASESTEP_NAME "/dev/DDS0_PM_ModPhaseStep"
#define DDS0_PM_MODPHASESTEP_RESET_VALUE 0
#define DDS0_PM_MODPHASESTEP_SPAN 16
#define DDS0_PM_MODPHASESTEP_TYPE "altera_avalon_pio"


/*
 * DDS0_PWM_Amplitude configuration
 *
 */

#define ALT_MODULE_CLASS_DDS0_PWM_Amplitude altera_avalon_pio
#define DDS0_PWM_AMPLITUDE_BASE 0x8130
#define DDS0_PWM_AMPLITUDE_BIT_CLEARING_EDGE_REGISTER 0
#define DDS0_PWM_AMPLITUDE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS0_PWM_AMPLITUDE_CAPTURE 0
#define DDS0_PWM_AMPLITUDE_DATA_WIDTH 16
#define DDS0_PWM_AMPLITUDE_DO_TEST_BENCH_WIRING 0
#define DDS0_PWM_AMPLITUDE_DRIVEN_SIM_VALUE 0
#define DDS0_PWM_AMPLITUDE_EDGE_TYPE "NONE"
#define DDS0_PWM_AMPLITUDE_FREQ 100000000
#define DDS0_PWM_AMPLITUDE_HAS_IN 0
#define DDS0_PWM_AMPLITUDE_HAS_OUT 1
#define DDS0_PWM_AMPLITUDE_HAS_TRI 0
#define DDS0_PWM_AMPLITUDE_IRQ -1
#define DDS0_PWM_AMPLITUDE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS0_PWM_AMPLITUDE_IRQ_TYPE "NONE"
#define DDS0_PWM_AMPLITUDE_NAME "/dev/DDS0_PWM_Amplitude"
#define DDS0_PWM_AMPLITUDE_RESET_VALUE 0
#define DDS0_PWM_AMPLITUDE_SPAN 16
#define DDS0_PWM_AMPLITUDE_TYPE "altera_avalon_pio"


/*
 * DDS0_PWM_Offset configuration
 *
 */

#define ALT_MODULE_CLASS_DDS0_PWM_Offset altera_avalon_pio
#define DDS0_PWM_OFFSET_BASE 0x8110
#define DDS0_PWM_OFFSET_BIT_CLEARING_EDGE_REGISTER 0
#define DDS0_PWM_OFFSET_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS0_PWM_OFFSET_CAPTURE 0
#define DDS0_PWM_OFFSET_DATA_WIDTH 16
#define DDS0_PWM_OFFSET_DO_TEST_BENCH_WIRING 0
#define DDS0_PWM_OFFSET_DRIVEN_SIM_VALUE 0
#define DDS0_PWM_OFFSET_EDGE_TYPE "NONE"
#define DDS0_PWM_OFFSET_FREQ 100000000
#define DDS0_PWM_OFFSET_HAS_IN 0
#define DDS0_PWM_OFFSET_HAS_OUT 1
#define DDS0_PWM_OFFSET_HAS_TRI 0
#define DDS0_PWM_OFFSET_IRQ -1
#define DDS0_PWM_OFFSET_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS0_PWM_OFFSET_IRQ_TYPE "NONE"
#define DDS0_PWM_OFFSET_NAME "/dev/DDS0_PWM_Offset"
#define DDS0_PWM_OFFSET_RESET_VALUE 0
#define DDS0_PWM_OFFSET_SPAN 16
#define DDS0_PWM_OFFSET_TYPE "altera_avalon_pio"


/*
 * DDS0_PhaseOffset configuration
 *
 */

#define ALT_MODULE_CLASS_DDS0_PhaseOffset altera_avalon_pio
#define DDS0_PHASEOFFSET_BASE 0x80f0
#define DDS0_PHASEOFFSET_BIT_CLEARING_EDGE_REGISTER 0
#define DDS0_PHASEOFFSET_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS0_PHASEOFFSET_CAPTURE 0
#define DDS0_PHASEOFFSET_DATA_WIDTH 32
#define DDS0_PHASEOFFSET_DO_TEST_BENCH_WIRING 0
#define DDS0_PHASEOFFSET_DRIVEN_SIM_VALUE 0
#define DDS0_PHASEOFFSET_EDGE_TYPE "NONE"
#define DDS0_PHASEOFFSET_FREQ 100000000
#define DDS0_PHASEOFFSET_HAS_IN 0
#define DDS0_PHASEOFFSET_HAS_OUT 1
#define DDS0_PHASEOFFSET_HAS_TRI 0
#define DDS0_PHASEOFFSET_IRQ -1
#define DDS0_PHASEOFFSET_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS0_PHASEOFFSET_IRQ_TYPE "NONE"
#define DDS0_PHASEOFFSET_NAME "/dev/DDS0_PhaseOffset"
#define DDS0_PHASEOFFSET_RESET_VALUE 0
#define DDS0_PHASEOFFSET_SPAN 16
#define DDS0_PHASEOFFSET_TYPE "altera_avalon_pio"


/*
 * DDS0_PhaseStep configuration
 *
 */

#define ALT_MODULE_CLASS_DDS0_PhaseStep altera_avalon_pio
#define DDS0_PHASESTEP_BASE 0x80d0
#define DDS0_PHASESTEP_BIT_CLEARING_EDGE_REGISTER 0
#define DDS0_PHASESTEP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS0_PHASESTEP_CAPTURE 0
#define DDS0_PHASESTEP_DATA_WIDTH 32
#define DDS0_PHASESTEP_DO_TEST_BENCH_WIRING 0
#define DDS0_PHASESTEP_DRIVEN_SIM_VALUE 0
#define DDS0_PHASESTEP_EDGE_TYPE "NONE"
#define DDS0_PHASESTEP_FREQ 100000000
#define DDS0_PHASESTEP_HAS_IN 0
#define DDS0_PHASESTEP_HAS_OUT 1
#define DDS0_PHASESTEP_HAS_TRI 0
#define DDS0_PHASESTEP_IRQ -1
#define DDS0_PHASESTEP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS0_PHASESTEP_IRQ_TYPE "NONE"
#define DDS0_PHASESTEP_NAME "/dev/DDS0_PhaseStep"
#define DDS0_PHASESTEP_RESET_VALUE 0
#define DDS0_PHASESTEP_SPAN 16
#define DDS0_PHASESTEP_TYPE "altera_avalon_pio"


/*
 * DDS1_AM_ModIndex configuration
 *
 */

#define ALT_MODULE_CLASS_DDS1_AM_ModIndex altera_avalon_pio
#define DDS1_AM_MODINDEX_BASE 0x8200
#define DDS1_AM_MODINDEX_BIT_CLEARING_EDGE_REGISTER 0
#define DDS1_AM_MODINDEX_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS1_AM_MODINDEX_CAPTURE 0
#define DDS1_AM_MODINDEX_DATA_WIDTH 32
#define DDS1_AM_MODINDEX_DO_TEST_BENCH_WIRING 0
#define DDS1_AM_MODINDEX_DRIVEN_SIM_VALUE 0
#define DDS1_AM_MODINDEX_EDGE_TYPE "NONE"
#define DDS1_AM_MODINDEX_FREQ 100000000
#define DDS1_AM_MODINDEX_HAS_IN 0
#define DDS1_AM_MODINDEX_HAS_OUT 1
#define DDS1_AM_MODINDEX_HAS_TRI 0
#define DDS1_AM_MODINDEX_IRQ -1
#define DDS1_AM_MODINDEX_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS1_AM_MODINDEX_IRQ_TYPE "NONE"
#define DDS1_AM_MODINDEX_NAME "/dev/DDS1_AM_ModIndex"
#define DDS1_AM_MODINDEX_RESET_VALUE 0
#define DDS1_AM_MODINDEX_SPAN 16
#define DDS1_AM_MODINDEX_TYPE "altera_avalon_pio"


/*
 * DDS1_AM_ModPhaseStep configuration
 *
 */

#define ALT_MODULE_CLASS_DDS1_AM_ModPhaseStep altera_avalon_pio
#define DDS1_AM_MODPHASESTEP_BASE 0x81e0
#define DDS1_AM_MODPHASESTEP_BIT_CLEARING_EDGE_REGISTER 0
#define DDS1_AM_MODPHASESTEP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS1_AM_MODPHASESTEP_CAPTURE 0
#define DDS1_AM_MODPHASESTEP_DATA_WIDTH 32
#define DDS1_AM_MODPHASESTEP_DO_TEST_BENCH_WIRING 0
#define DDS1_AM_MODPHASESTEP_DRIVEN_SIM_VALUE 0
#define DDS1_AM_MODPHASESTEP_EDGE_TYPE "NONE"
#define DDS1_AM_MODPHASESTEP_FREQ 100000000
#define DDS1_AM_MODPHASESTEP_HAS_IN 0
#define DDS1_AM_MODPHASESTEP_HAS_OUT 1
#define DDS1_AM_MODPHASESTEP_HAS_TRI 0
#define DDS1_AM_MODPHASESTEP_IRQ -1
#define DDS1_AM_MODPHASESTEP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS1_AM_MODPHASESTEP_IRQ_TYPE "NONE"
#define DDS1_AM_MODPHASESTEP_NAME "/dev/DDS1_AM_ModPhaseStep"
#define DDS1_AM_MODPHASESTEP_RESET_VALUE 0
#define DDS1_AM_MODPHASESTEP_SPAN 16
#define DDS1_AM_MODPHASESTEP_TYPE "altera_avalon_pio"


/*
 * DDS1_FM_ModDeviationPhase configuration
 *
 */

#define ALT_MODULE_CLASS_DDS1_FM_ModDeviationPhase altera_avalon_pio
#define DDS1_FM_MODDEVIATIONPHASE_BASE 0x81c0
#define DDS1_FM_MODDEVIATIONPHASE_BIT_CLEARING_EDGE_REGISTER 0
#define DDS1_FM_MODDEVIATIONPHASE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS1_FM_MODDEVIATIONPHASE_CAPTURE 0
#define DDS1_FM_MODDEVIATIONPHASE_DATA_WIDTH 32
#define DDS1_FM_MODDEVIATIONPHASE_DO_TEST_BENCH_WIRING 0
#define DDS1_FM_MODDEVIATIONPHASE_DRIVEN_SIM_VALUE 0
#define DDS1_FM_MODDEVIATIONPHASE_EDGE_TYPE "NONE"
#define DDS1_FM_MODDEVIATIONPHASE_FREQ 100000000
#define DDS1_FM_MODDEVIATIONPHASE_HAS_IN 0
#define DDS1_FM_MODDEVIATIONPHASE_HAS_OUT 1
#define DDS1_FM_MODDEVIATIONPHASE_HAS_TRI 0
#define DDS1_FM_MODDEVIATIONPHASE_IRQ -1
#define DDS1_FM_MODDEVIATIONPHASE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS1_FM_MODDEVIATIONPHASE_IRQ_TYPE "NONE"
#define DDS1_FM_MODDEVIATIONPHASE_NAME "/dev/DDS1_FM_ModDeviationPhase"
#define DDS1_FM_MODDEVIATIONPHASE_RESET_VALUE 0
#define DDS1_FM_MODDEVIATIONPHASE_SPAN 16
#define DDS1_FM_MODDEVIATIONPHASE_TYPE "altera_avalon_pio"


/*
 * DDS1_FM_ModPhaseStep configuration
 *
 */

#define ALT_MODULE_CLASS_DDS1_FM_ModPhaseStep altera_avalon_pio
#define DDS1_FM_MODPHASESTEP_BASE 0x81a0
#define DDS1_FM_MODPHASESTEP_BIT_CLEARING_EDGE_REGISTER 0
#define DDS1_FM_MODPHASESTEP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS1_FM_MODPHASESTEP_CAPTURE 0
#define DDS1_FM_MODPHASESTEP_DATA_WIDTH 32
#define DDS1_FM_MODPHASESTEP_DO_TEST_BENCH_WIRING 0
#define DDS1_FM_MODPHASESTEP_DRIVEN_SIM_VALUE 0
#define DDS1_FM_MODPHASESTEP_EDGE_TYPE "NONE"
#define DDS1_FM_MODPHASESTEP_FREQ 100000000
#define DDS1_FM_MODPHASESTEP_HAS_IN 0
#define DDS1_FM_MODPHASESTEP_HAS_OUT 1
#define DDS1_FM_MODPHASESTEP_HAS_TRI 0
#define DDS1_FM_MODPHASESTEP_IRQ -1
#define DDS1_FM_MODPHASESTEP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS1_FM_MODPHASESTEP_IRQ_TYPE "NONE"
#define DDS1_FM_MODPHASESTEP_NAME "/dev/DDS1_FM_ModPhaseStep"
#define DDS1_FM_MODPHASESTEP_RESET_VALUE 0
#define DDS1_FM_MODPHASESTEP_SPAN 16
#define DDS1_FM_MODPHASESTEP_TYPE "altera_avalon_pio"


/*
 * DDS1_OutputRelay configuration
 *
 */

#define ALT_MODULE_CLASS_DDS1_OutputRelay altera_avalon_pio
#define DDS1_OUTPUTRELAY_BASE 0x8180
#define DDS1_OUTPUTRELAY_BIT_CLEARING_EDGE_REGISTER 0
#define DDS1_OUTPUTRELAY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS1_OUTPUTRELAY_CAPTURE 0
#define DDS1_OUTPUTRELAY_DATA_WIDTH 1
#define DDS1_OUTPUTRELAY_DO_TEST_BENCH_WIRING 0
#define DDS1_OUTPUTRELAY_DRIVEN_SIM_VALUE 0
#define DDS1_OUTPUTRELAY_EDGE_TYPE "NONE"
#define DDS1_OUTPUTRELAY_FREQ 100000000
#define DDS1_OUTPUTRELAY_HAS_IN 0
#define DDS1_OUTPUTRELAY_HAS_OUT 1
#define DDS1_OUTPUTRELAY_HAS_TRI 0
#define DDS1_OUTPUTRELAY_IRQ -1
#define DDS1_OUTPUTRELAY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS1_OUTPUTRELAY_IRQ_TYPE "NONE"
#define DDS1_OUTPUTRELAY_NAME "/dev/DDS1_OutputRelay"
#define DDS1_OUTPUTRELAY_RESET_VALUE 0
#define DDS1_OUTPUTRELAY_SPAN 16
#define DDS1_OUTPUTRELAY_TYPE "altera_avalon_pio"


/*
 * DDS1_PM_ModIndex configuration
 *
 */

#define ALT_MODULE_CLASS_DDS1_PM_ModIndex altera_avalon_pio
#define DDS1_PM_MODINDEX_BASE 0x8160
#define DDS1_PM_MODINDEX_BIT_CLEARING_EDGE_REGISTER 0
#define DDS1_PM_MODINDEX_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS1_PM_MODINDEX_CAPTURE 0
#define DDS1_PM_MODINDEX_DATA_WIDTH 32
#define DDS1_PM_MODINDEX_DO_TEST_BENCH_WIRING 0
#define DDS1_PM_MODINDEX_DRIVEN_SIM_VALUE 0
#define DDS1_PM_MODINDEX_EDGE_TYPE "NONE"
#define DDS1_PM_MODINDEX_FREQ 100000000
#define DDS1_PM_MODINDEX_HAS_IN 0
#define DDS1_PM_MODINDEX_HAS_OUT 1
#define DDS1_PM_MODINDEX_HAS_TRI 0
#define DDS1_PM_MODINDEX_IRQ -1
#define DDS1_PM_MODINDEX_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS1_PM_MODINDEX_IRQ_TYPE "NONE"
#define DDS1_PM_MODINDEX_NAME "/dev/DDS1_PM_ModIndex"
#define DDS1_PM_MODINDEX_RESET_VALUE 0
#define DDS1_PM_MODINDEX_SPAN 16
#define DDS1_PM_MODINDEX_TYPE "altera_avalon_pio"


/*
 * DDS1_PM_ModPhaseStep configuration
 *
 */

#define ALT_MODULE_CLASS_DDS1_PM_ModPhaseStep altera_avalon_pio
#define DDS1_PM_MODPHASESTEP_BASE 0x8140
#define DDS1_PM_MODPHASESTEP_BIT_CLEARING_EDGE_REGISTER 0
#define DDS1_PM_MODPHASESTEP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS1_PM_MODPHASESTEP_CAPTURE 0
#define DDS1_PM_MODPHASESTEP_DATA_WIDTH 32
#define DDS1_PM_MODPHASESTEP_DO_TEST_BENCH_WIRING 0
#define DDS1_PM_MODPHASESTEP_DRIVEN_SIM_VALUE 0
#define DDS1_PM_MODPHASESTEP_EDGE_TYPE "NONE"
#define DDS1_PM_MODPHASESTEP_FREQ 100000000
#define DDS1_PM_MODPHASESTEP_HAS_IN 0
#define DDS1_PM_MODPHASESTEP_HAS_OUT 1
#define DDS1_PM_MODPHASESTEP_HAS_TRI 0
#define DDS1_PM_MODPHASESTEP_IRQ -1
#define DDS1_PM_MODPHASESTEP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS1_PM_MODPHASESTEP_IRQ_TYPE "NONE"
#define DDS1_PM_MODPHASESTEP_NAME "/dev/DDS1_PM_ModPhaseStep"
#define DDS1_PM_MODPHASESTEP_RESET_VALUE 0
#define DDS1_PM_MODPHASESTEP_SPAN 16
#define DDS1_PM_MODPHASESTEP_TYPE "altera_avalon_pio"


/*
 * DDS1_PWM_Amplitude configuration
 *
 */

#define ALT_MODULE_CLASS_DDS1_PWM_Amplitude altera_avalon_pio
#define DDS1_PWM_AMPLITUDE_BASE 0x8120
#define DDS1_PWM_AMPLITUDE_BIT_CLEARING_EDGE_REGISTER 0
#define DDS1_PWM_AMPLITUDE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS1_PWM_AMPLITUDE_CAPTURE 0
#define DDS1_PWM_AMPLITUDE_DATA_WIDTH 16
#define DDS1_PWM_AMPLITUDE_DO_TEST_BENCH_WIRING 0
#define DDS1_PWM_AMPLITUDE_DRIVEN_SIM_VALUE 0
#define DDS1_PWM_AMPLITUDE_EDGE_TYPE "NONE"
#define DDS1_PWM_AMPLITUDE_FREQ 100000000
#define DDS1_PWM_AMPLITUDE_HAS_IN 0
#define DDS1_PWM_AMPLITUDE_HAS_OUT 1
#define DDS1_PWM_AMPLITUDE_HAS_TRI 0
#define DDS1_PWM_AMPLITUDE_IRQ -1
#define DDS1_PWM_AMPLITUDE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS1_PWM_AMPLITUDE_IRQ_TYPE "NONE"
#define DDS1_PWM_AMPLITUDE_NAME "/dev/DDS1_PWM_Amplitude"
#define DDS1_PWM_AMPLITUDE_RESET_VALUE 0
#define DDS1_PWM_AMPLITUDE_SPAN 16
#define DDS1_PWM_AMPLITUDE_TYPE "altera_avalon_pio"


/*
 * DDS1_PWM_Offset configuration
 *
 */

#define ALT_MODULE_CLASS_DDS1_PWM_Offset altera_avalon_pio
#define DDS1_PWM_OFFSET_BASE 0x8100
#define DDS1_PWM_OFFSET_BIT_CLEARING_EDGE_REGISTER 0
#define DDS1_PWM_OFFSET_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS1_PWM_OFFSET_CAPTURE 0
#define DDS1_PWM_OFFSET_DATA_WIDTH 16
#define DDS1_PWM_OFFSET_DO_TEST_BENCH_WIRING 0
#define DDS1_PWM_OFFSET_DRIVEN_SIM_VALUE 0
#define DDS1_PWM_OFFSET_EDGE_TYPE "NONE"
#define DDS1_PWM_OFFSET_FREQ 100000000
#define DDS1_PWM_OFFSET_HAS_IN 0
#define DDS1_PWM_OFFSET_HAS_OUT 1
#define DDS1_PWM_OFFSET_HAS_TRI 0
#define DDS1_PWM_OFFSET_IRQ -1
#define DDS1_PWM_OFFSET_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS1_PWM_OFFSET_IRQ_TYPE "NONE"
#define DDS1_PWM_OFFSET_NAME "/dev/DDS1_PWM_Offset"
#define DDS1_PWM_OFFSET_RESET_VALUE 0
#define DDS1_PWM_OFFSET_SPAN 16
#define DDS1_PWM_OFFSET_TYPE "altera_avalon_pio"


/*
 * DDS1_PhaseOffset configuration
 *
 */

#define ALT_MODULE_CLASS_DDS1_PhaseOffset altera_avalon_pio
#define DDS1_PHASEOFFSET_BASE 0x80e0
#define DDS1_PHASEOFFSET_BIT_CLEARING_EDGE_REGISTER 0
#define DDS1_PHASEOFFSET_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS1_PHASEOFFSET_CAPTURE 0
#define DDS1_PHASEOFFSET_DATA_WIDTH 32
#define DDS1_PHASEOFFSET_DO_TEST_BENCH_WIRING 0
#define DDS1_PHASEOFFSET_DRIVEN_SIM_VALUE 0
#define DDS1_PHASEOFFSET_EDGE_TYPE "NONE"
#define DDS1_PHASEOFFSET_FREQ 100000000
#define DDS1_PHASEOFFSET_HAS_IN 0
#define DDS1_PHASEOFFSET_HAS_OUT 1
#define DDS1_PHASEOFFSET_HAS_TRI 0
#define DDS1_PHASEOFFSET_IRQ -1
#define DDS1_PHASEOFFSET_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS1_PHASEOFFSET_IRQ_TYPE "NONE"
#define DDS1_PHASEOFFSET_NAME "/dev/DDS1_PhaseOffset"
#define DDS1_PHASEOFFSET_RESET_VALUE 0
#define DDS1_PHASEOFFSET_SPAN 16
#define DDS1_PHASEOFFSET_TYPE "altera_avalon_pio"


/*
 * DDS1_PhaseStep configuration
 *
 */

#define ALT_MODULE_CLASS_DDS1_PhaseStep altera_avalon_pio
#define DDS1_PHASESTEP_BASE 0x80c0
#define DDS1_PHASESTEP_BIT_CLEARING_EDGE_REGISTER 0
#define DDS1_PHASESTEP_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS1_PHASESTEP_CAPTURE 0
#define DDS1_PHASESTEP_DATA_WIDTH 32
#define DDS1_PHASESTEP_DO_TEST_BENCH_WIRING 0
#define DDS1_PHASESTEP_DRIVEN_SIM_VALUE 0
#define DDS1_PHASESTEP_EDGE_TYPE "NONE"
#define DDS1_PHASESTEP_FREQ 100000000
#define DDS1_PHASESTEP_HAS_IN 0
#define DDS1_PHASESTEP_HAS_OUT 1
#define DDS1_PHASESTEP_HAS_TRI 0
#define DDS1_PHASESTEP_IRQ -1
#define DDS1_PHASESTEP_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS1_PHASESTEP_IRQ_TYPE "NONE"
#define DDS1_PHASESTEP_NAME "/dev/DDS1_PhaseStep"
#define DDS1_PHASESTEP_RESET_VALUE 0
#define DDS1_PHASESTEP_SPAN 16
#define DDS1_PHASESTEP_TYPE "altera_avalon_pio"


/*
 * DDS_RESET configuration
 *
 */

#define ALT_MODULE_CLASS_DDS_RESET altera_avalon_pio
#define DDS_RESET_BASE 0x8070
#define DDS_RESET_BIT_CLEARING_EDGE_REGISTER 0
#define DDS_RESET_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DDS_RESET_CAPTURE 0
#define DDS_RESET_DATA_WIDTH 2
#define DDS_RESET_DO_TEST_BENCH_WIRING 0
#define DDS_RESET_DRIVEN_SIM_VALUE 0
#define DDS_RESET_EDGE_TYPE "NONE"
#define DDS_RESET_FREQ 100000000
#define DDS_RESET_HAS_IN 0
#define DDS_RESET_HAS_OUT 1
#define DDS_RESET_HAS_TRI 0
#define DDS_RESET_IRQ -1
#define DDS_RESET_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DDS_RESET_IRQ_TYPE "NONE"
#define DDS_RESET_NAME "/dev/DDS_RESET"
#define DDS_RESET_RESET_VALUE 0
#define DDS_RESET_SPAN 16
#define DDS_RESET_TYPE "altera_avalon_pio"


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_DMA
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SPI
#define __ALTERA_AVALON_TIMER
#define __ALTERA_NIOS2_GEN2
#define __ALTERA_ONCHIP_FLASH


/*
 * FLASH_csr configuration
 *
 */

#define ALT_MODULE_CLASS_FLASH_csr altera_onchip_flash
#define FLASH_CSR_BASE 0x89080
#define FLASH_CSR_BYTES_PER_PAGE 2048
#define FLASH_CSR_IRQ -1
#define FLASH_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FLASH_CSR_NAME "/dev/FLASH_csr"
#define FLASH_CSR_READ_ONLY_MODE 0
#define FLASH_CSR_SECTOR1_ENABLED 1
#define FLASH_CSR_SECTOR1_END_ADDR 0x3fff
#define FLASH_CSR_SECTOR1_START_ADDR 0
#define FLASH_CSR_SECTOR2_ENABLED 1
#define FLASH_CSR_SECTOR2_END_ADDR 0x7fff
#define FLASH_CSR_SECTOR2_START_ADDR 0x4000
#define FLASH_CSR_SECTOR3_ENABLED 1
#define FLASH_CSR_SECTOR3_END_ADDR 0x1c7ff
#define FLASH_CSR_SECTOR3_START_ADDR 0x8000
#define FLASH_CSR_SECTOR4_ENABLED 1
#define FLASH_CSR_SECTOR4_END_ADDR 0x2afff
#define FLASH_CSR_SECTOR4_START_ADDR 0x1c800
#define FLASH_CSR_SECTOR5_ENABLED 0
#define FLASH_CSR_SECTOR5_END_ADDR 0xffffffff
#define FLASH_CSR_SECTOR5_START_ADDR 0xffffffff
#define FLASH_CSR_SPAN 8
#define FLASH_CSR_TYPE "altera_onchip_flash"


/*
 * FLASH_data configuration
 *
 */

#define ALT_MODULE_CLASS_FLASH_data altera_onchip_flash
#define FLASH_DATA_BASE 0x40000
#define FLASH_DATA_BYTES_PER_PAGE 2048
#define FLASH_DATA_IRQ -1
#define FLASH_DATA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define FLASH_DATA_NAME "/dev/FLASH_data"
#define FLASH_DATA_READ_ONLY_MODE 0
#define FLASH_DATA_SECTOR1_ENABLED 1
#define FLASH_DATA_SECTOR1_END_ADDR 0x3fff
#define FLASH_DATA_SECTOR1_START_ADDR 0
#define FLASH_DATA_SECTOR2_ENABLED 1
#define FLASH_DATA_SECTOR2_END_ADDR 0x7fff
#define FLASH_DATA_SECTOR2_START_ADDR 0x4000
#define FLASH_DATA_SECTOR3_ENABLED 1
#define FLASH_DATA_SECTOR3_END_ADDR 0x1c7ff
#define FLASH_DATA_SECTOR3_START_ADDR 0x8000
#define FLASH_DATA_SECTOR4_ENABLED 1
#define FLASH_DATA_SECTOR4_END_ADDR 0x2afff
#define FLASH_DATA_SECTOR4_START_ADDR 0x1c800
#define FLASH_DATA_SECTOR5_ENABLED 0
#define FLASH_DATA_SECTOR5_END_ADDR 0xffffffff
#define FLASH_DATA_SECTOR5_START_ADDR 0xffffffff
#define FLASH_DATA_SPAN 176128
#define FLASH_DATA_TYPE "altera_onchip_flash"


/*
 * JTAG_UART configuration
 *
 */

#define ALT_MODULE_CLASS_JTAG_UART altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x89088
#define JTAG_UART_IRQ 1
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/JTAG_UART"
#define JTAG_UART_READ_DEPTH 8
#define JTAG_UART_READ_THRESHOLD 0
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 8
#define JTAG_UART_WRITE_THRESHOLD 0


/*
 * KEYPAD configuration
 *
 */

#define ALT_MODULE_CLASS_KEYPAD altera_avalon_pio
#define KEYPAD_BASE 0x80b0
#define KEYPAD_BIT_CLEARING_EDGE_REGISTER 0
#define KEYPAD_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEYPAD_CAPTURE 1
#define KEYPAD_DATA_WIDTH 8
#define KEYPAD_DO_TEST_BENCH_WIRING 0
#define KEYPAD_DRIVEN_SIM_VALUE 0
#define KEYPAD_EDGE_TYPE "FALLING"
#define KEYPAD_FREQ 100000000
#define KEYPAD_HAS_IN 1
#define KEYPAD_HAS_OUT 0
#define KEYPAD_HAS_TRI 0
#define KEYPAD_IRQ 2
#define KEYPAD_IRQ_INTERRUPT_CONTROLLER_ID 0
#define KEYPAD_IRQ_TYPE "EDGE"
#define KEYPAD_NAME "/dev/KEYPAD"
#define KEYPAD_RESET_VALUE 0
#define KEYPAD_SPAN 16
#define KEYPAD_TYPE "altera_avalon_pio"


/*
 * LCD_BackLight_PWM configuration
 *
 */

#define ALT_MODULE_CLASS_LCD_BackLight_PWM altera_avalon_pio
#define LCD_BACKLIGHT_PWM_BASE 0x89070
#define LCD_BACKLIGHT_PWM_BIT_CLEARING_EDGE_REGISTER 0
#define LCD_BACKLIGHT_PWM_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LCD_BACKLIGHT_PWM_CAPTURE 0
#define LCD_BACKLIGHT_PWM_DATA_WIDTH 8
#define LCD_BACKLIGHT_PWM_DO_TEST_BENCH_WIRING 0
#define LCD_BACKLIGHT_PWM_DRIVEN_SIM_VALUE 0
#define LCD_BACKLIGHT_PWM_EDGE_TYPE "NONE"
#define LCD_BACKLIGHT_PWM_FREQ 100000000
#define LCD_BACKLIGHT_PWM_HAS_IN 0
#define LCD_BACKLIGHT_PWM_HAS_OUT 1
#define LCD_BACKLIGHT_PWM_HAS_TRI 0
#define LCD_BACKLIGHT_PWM_IRQ -1
#define LCD_BACKLIGHT_PWM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LCD_BACKLIGHT_PWM_IRQ_TYPE "NONE"
#define LCD_BACKLIGHT_PWM_NAME "/dev/LCD_BackLight_PWM"
#define LCD_BACKLIGHT_PWM_RESET_VALUE 0
#define LCD_BACKLIGHT_PWM_SPAN 16
#define LCD_BACKLIGHT_PWM_TYPE "altera_avalon_pio"


/*
 * LCD_Control configuration
 *
 */

#define ALT_MODULE_CLASS_LCD_Control altera_avalon_pio
#define LCD_CONTROL_BASE 0x89040
#define LCD_CONTROL_BIT_CLEARING_EDGE_REGISTER 0
#define LCD_CONTROL_BIT_MODIFYING_OUTPUT_REGISTER 1
#define LCD_CONTROL_CAPTURE 0
#define LCD_CONTROL_DATA_WIDTH 5
#define LCD_CONTROL_DO_TEST_BENCH_WIRING 0
#define LCD_CONTROL_DRIVEN_SIM_VALUE 0
#define LCD_CONTROL_EDGE_TYPE "NONE"
#define LCD_CONTROL_FREQ 100000000
#define LCD_CONTROL_HAS_IN 0
#define LCD_CONTROL_HAS_OUT 1
#define LCD_CONTROL_HAS_TRI 0
#define LCD_CONTROL_IRQ -1
#define LCD_CONTROL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LCD_CONTROL_IRQ_TYPE "NONE"
#define LCD_CONTROL_NAME "/dev/LCD_Control"
#define LCD_CONTROL_RESET_VALUE 0
#define LCD_CONTROL_SPAN 32
#define LCD_CONTROL_TYPE "altera_avalon_pio"


/*
 * LCD_DMA configuration
 *
 */

#define ALT_MODULE_CLASS_LCD_DMA altera_avalon_dma
#define LCD_DMA_ALLOW_BYTE_TRANSACTIONS 1
#define LCD_DMA_ALLOW_DOUBLEWORD_TRANSACTIONS 0
#define LCD_DMA_ALLOW_HW_TRANSACTIONS 0
#define LCD_DMA_ALLOW_QUADWORD_TRANSACTIONS 0
#define LCD_DMA_ALLOW_WORD_TRANSACTIONS 0
#define LCD_DMA_BASE 0x8040
#define LCD_DMA_IRQ 8
#define LCD_DMA_IRQ_INTERRUPT_CONTROLLER_ID 0
#define LCD_DMA_LENGTHWIDTH 12
#define LCD_DMA_MAX_BURST_SIZE 128
#define LCD_DMA_NAME "/dev/LCD_DMA"
#define LCD_DMA_SPAN 32
#define LCD_DMA_TYPE "altera_avalon_dma"


/*
 * LCD_Data configuration
 *
 */

#define ALT_MODULE_CLASS_LCD_Data altera_avalon_pio
#define LCD_DATA_BASE 0x89060
#define LCD_DATA_BIT_CLEARING_EDGE_REGISTER 0
#define LCD_DATA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LCD_DATA_CAPTURE 0
#define LCD_DATA_DATA_WIDTH 8
#define LCD_DATA_DO_TEST_BENCH_WIRING 0
#define LCD_DATA_DRIVEN_SIM_VALUE 0
#define LCD_DATA_EDGE_TYPE "NONE"
#define LCD_DATA_FREQ 100000000
#define LCD_DATA_HAS_IN 0
#define LCD_DATA_HAS_OUT 1
#define LCD_DATA_HAS_TRI 0
#define LCD_DATA_IRQ -1
#define LCD_DATA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LCD_DATA_IRQ_TYPE "NONE"
#define LCD_DATA_NAME "/dev/LCD_Data"
#define LCD_DATA_RESET_VALUE 0
#define LCD_DATA_SPAN 16
#define LCD_DATA_TYPE "altera_avalon_pio"


/*
 * LOOKUP_RAM_ISR configuration
 *
 */

#define ALT_MODULE_CLASS_LOOKUP_RAM_ISR altera_avalon_pio
#define LOOKUP_RAM_ISR_BASE 0x8060
#define LOOKUP_RAM_ISR_BIT_CLEARING_EDGE_REGISTER 0
#define LOOKUP_RAM_ISR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LOOKUP_RAM_ISR_CAPTURE 1
#define LOOKUP_RAM_ISR_DATA_WIDTH 6
#define LOOKUP_RAM_ISR_DO_TEST_BENCH_WIRING 0
#define LOOKUP_RAM_ISR_DRIVEN_SIM_VALUE 0
#define LOOKUP_RAM_ISR_EDGE_TYPE "ANY"
#define LOOKUP_RAM_ISR_FREQ 100000000
#define LOOKUP_RAM_ISR_HAS_IN 1
#define LOOKUP_RAM_ISR_HAS_OUT 0
#define LOOKUP_RAM_ISR_HAS_TRI 0
#define LOOKUP_RAM_ISR_IRQ 7
#define LOOKUP_RAM_ISR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define LOOKUP_RAM_ISR_IRQ_TYPE "EDGE"
#define LOOKUP_RAM_ISR_NAME "/dev/LOOKUP_RAM_ISR"
#define LOOKUP_RAM_ISR_RESET_VALUE 0
#define LOOKUP_RAM_ISR_SPAN 16
#define LOOKUP_RAM_ISR_TYPE "altera_avalon_pio"


/*
 * LOOKUP_RAM_RAM_DDS0 configuration
 *
 */

#define ALT_MODULE_CLASS_LOOKUP_RAM_RAM_DDS0 altera_avalon_onchip_memory2
#define LOOKUP_RAM_RAM_DDS0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define LOOKUP_RAM_RAM_DDS0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define LOOKUP_RAM_RAM_DDS0_BASE 0xa000
#define LOOKUP_RAM_RAM_DDS0_CONTENTS_INFO ""
#define LOOKUP_RAM_RAM_DDS0_DUAL_PORT 1
#define LOOKUP_RAM_RAM_DDS0_GUI_RAM_BLOCK_TYPE "AUTO"
#define LOOKUP_RAM_RAM_DDS0_INIT_CONTENTS_FILE "NiosII_Processor_LOOKUP_RAM_RAM_DDS0"
#define LOOKUP_RAM_RAM_DDS0_INIT_MEM_CONTENT 0
#define LOOKUP_RAM_RAM_DDS0_INSTANCE_ID "NONE"
#define LOOKUP_RAM_RAM_DDS0_IRQ -1
#define LOOKUP_RAM_RAM_DDS0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LOOKUP_RAM_RAM_DDS0_NAME "/dev/LOOKUP_RAM_RAM_DDS0"
#define LOOKUP_RAM_RAM_DDS0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define LOOKUP_RAM_RAM_DDS0_RAM_BLOCK_TYPE "AUTO"
#define LOOKUP_RAM_RAM_DDS0_READ_DURING_WRITE_MODE "DONT_CARE"
#define LOOKUP_RAM_RAM_DDS0_SINGLE_CLOCK_OP 0
#define LOOKUP_RAM_RAM_DDS0_SIZE_MULTIPLE 1
#define LOOKUP_RAM_RAM_DDS0_SIZE_VALUE 2048
#define LOOKUP_RAM_RAM_DDS0_SPAN 2048
#define LOOKUP_RAM_RAM_DDS0_TYPE "altera_avalon_onchip_memory2"
#define LOOKUP_RAM_RAM_DDS0_WRITABLE 1


/*
 * LOOKUP_RAM_RAM_DDS0_AM configuration
 *
 */

#define ALT_MODULE_CLASS_LOOKUP_RAM_RAM_DDS0_AM altera_avalon_onchip_memory2
#define LOOKUP_RAM_RAM_DDS0_AM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define LOOKUP_RAM_RAM_DDS0_AM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define LOOKUP_RAM_RAM_DDS0_AM_BASE 0x9000
#define LOOKUP_RAM_RAM_DDS0_AM_CONTENTS_INFO ""
#define LOOKUP_RAM_RAM_DDS0_AM_DUAL_PORT 1
#define LOOKUP_RAM_RAM_DDS0_AM_GUI_RAM_BLOCK_TYPE "AUTO"
#define LOOKUP_RAM_RAM_DDS0_AM_INIT_CONTENTS_FILE "NiosII_Processor_LOOKUP_RAM_RAM_DDS0_AM"
#define LOOKUP_RAM_RAM_DDS0_AM_INIT_MEM_CONTENT 0
#define LOOKUP_RAM_RAM_DDS0_AM_INSTANCE_ID "NONE"
#define LOOKUP_RAM_RAM_DDS0_AM_IRQ -1
#define LOOKUP_RAM_RAM_DDS0_AM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LOOKUP_RAM_RAM_DDS0_AM_NAME "/dev/LOOKUP_RAM_RAM_DDS0_AM"
#define LOOKUP_RAM_RAM_DDS0_AM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define LOOKUP_RAM_RAM_DDS0_AM_RAM_BLOCK_TYPE "AUTO"
#define LOOKUP_RAM_RAM_DDS0_AM_READ_DURING_WRITE_MODE "DONT_CARE"
#define LOOKUP_RAM_RAM_DDS0_AM_SINGLE_CLOCK_OP 0
#define LOOKUP_RAM_RAM_DDS0_AM_SIZE_MULTIPLE 1
#define LOOKUP_RAM_RAM_DDS0_AM_SIZE_VALUE 2048
#define LOOKUP_RAM_RAM_DDS0_AM_SPAN 2048
#define LOOKUP_RAM_RAM_DDS0_AM_TYPE "altera_avalon_onchip_memory2"
#define LOOKUP_RAM_RAM_DDS0_AM_WRITABLE 1


/*
 * LOOKUP_RAM_RAM_DDS0_FM configuration
 *
 */

#define ALT_MODULE_CLASS_LOOKUP_RAM_RAM_DDS0_FM altera_avalon_onchip_memory2
#define LOOKUP_RAM_RAM_DDS0_FM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define LOOKUP_RAM_RAM_DDS0_FM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define LOOKUP_RAM_RAM_DDS0_FM_BASE 0x9800
#define LOOKUP_RAM_RAM_DDS0_FM_CONTENTS_INFO ""
#define LOOKUP_RAM_RAM_DDS0_FM_DUAL_PORT 1
#define LOOKUP_RAM_RAM_DDS0_FM_GUI_RAM_BLOCK_TYPE "AUTO"
#define LOOKUP_RAM_RAM_DDS0_FM_INIT_CONTENTS_FILE "NiosII_Processor_LOOKUP_RAM_RAM_DDS0_FM"
#define LOOKUP_RAM_RAM_DDS0_FM_INIT_MEM_CONTENT 0
#define LOOKUP_RAM_RAM_DDS0_FM_INSTANCE_ID "NONE"
#define LOOKUP_RAM_RAM_DDS0_FM_IRQ -1
#define LOOKUP_RAM_RAM_DDS0_FM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LOOKUP_RAM_RAM_DDS0_FM_NAME "/dev/LOOKUP_RAM_RAM_DDS0_FM"
#define LOOKUP_RAM_RAM_DDS0_FM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define LOOKUP_RAM_RAM_DDS0_FM_RAM_BLOCK_TYPE "AUTO"
#define LOOKUP_RAM_RAM_DDS0_FM_READ_DURING_WRITE_MODE "DONT_CARE"
#define LOOKUP_RAM_RAM_DDS0_FM_SINGLE_CLOCK_OP 0
#define LOOKUP_RAM_RAM_DDS0_FM_SIZE_MULTIPLE 1
#define LOOKUP_RAM_RAM_DDS0_FM_SIZE_VALUE 2048
#define LOOKUP_RAM_RAM_DDS0_FM_SPAN 2048
#define LOOKUP_RAM_RAM_DDS0_FM_TYPE "altera_avalon_onchip_memory2"
#define LOOKUP_RAM_RAM_DDS0_FM_WRITABLE 1


/*
 * LOOKUP_RAM_RAM_DDS1 configuration
 *
 */

#define ALT_MODULE_CLASS_LOOKUP_RAM_RAM_DDS1 altera_avalon_onchip_memory2
#define LOOKUP_RAM_RAM_DDS1_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define LOOKUP_RAM_RAM_DDS1_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define LOOKUP_RAM_RAM_DDS1_BASE 0xb800
#define LOOKUP_RAM_RAM_DDS1_CONTENTS_INFO ""
#define LOOKUP_RAM_RAM_DDS1_DUAL_PORT 1
#define LOOKUP_RAM_RAM_DDS1_GUI_RAM_BLOCK_TYPE "AUTO"
#define LOOKUP_RAM_RAM_DDS1_INIT_CONTENTS_FILE "NiosII_Processor_LOOKUP_RAM_RAM_DDS1"
#define LOOKUP_RAM_RAM_DDS1_INIT_MEM_CONTENT 0
#define LOOKUP_RAM_RAM_DDS1_INSTANCE_ID "NONE"
#define LOOKUP_RAM_RAM_DDS1_IRQ -1
#define LOOKUP_RAM_RAM_DDS1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LOOKUP_RAM_RAM_DDS1_NAME "/dev/LOOKUP_RAM_RAM_DDS1"
#define LOOKUP_RAM_RAM_DDS1_NON_DEFAULT_INIT_FILE_ENABLED 0
#define LOOKUP_RAM_RAM_DDS1_RAM_BLOCK_TYPE "AUTO"
#define LOOKUP_RAM_RAM_DDS1_READ_DURING_WRITE_MODE "DONT_CARE"
#define LOOKUP_RAM_RAM_DDS1_SINGLE_CLOCK_OP 0
#define LOOKUP_RAM_RAM_DDS1_SIZE_MULTIPLE 1
#define LOOKUP_RAM_RAM_DDS1_SIZE_VALUE 2048
#define LOOKUP_RAM_RAM_DDS1_SPAN 2048
#define LOOKUP_RAM_RAM_DDS1_TYPE "altera_avalon_onchip_memory2"
#define LOOKUP_RAM_RAM_DDS1_WRITABLE 1


/*
 * LOOKUP_RAM_RAM_DDS1_AM configuration
 *
 */

#define ALT_MODULE_CLASS_LOOKUP_RAM_RAM_DDS1_AM altera_avalon_onchip_memory2
#define LOOKUP_RAM_RAM_DDS1_AM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define LOOKUP_RAM_RAM_DDS1_AM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define LOOKUP_RAM_RAM_DDS1_AM_BASE 0xa800
#define LOOKUP_RAM_RAM_DDS1_AM_CONTENTS_INFO ""
#define LOOKUP_RAM_RAM_DDS1_AM_DUAL_PORT 1
#define LOOKUP_RAM_RAM_DDS1_AM_GUI_RAM_BLOCK_TYPE "AUTO"
#define LOOKUP_RAM_RAM_DDS1_AM_INIT_CONTENTS_FILE "NiosII_Processor_LOOKUP_RAM_RAM_DDS1_AM"
#define LOOKUP_RAM_RAM_DDS1_AM_INIT_MEM_CONTENT 0
#define LOOKUP_RAM_RAM_DDS1_AM_INSTANCE_ID "NONE"
#define LOOKUP_RAM_RAM_DDS1_AM_IRQ -1
#define LOOKUP_RAM_RAM_DDS1_AM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LOOKUP_RAM_RAM_DDS1_AM_NAME "/dev/LOOKUP_RAM_RAM_DDS1_AM"
#define LOOKUP_RAM_RAM_DDS1_AM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define LOOKUP_RAM_RAM_DDS1_AM_RAM_BLOCK_TYPE "AUTO"
#define LOOKUP_RAM_RAM_DDS1_AM_READ_DURING_WRITE_MODE "DONT_CARE"
#define LOOKUP_RAM_RAM_DDS1_AM_SINGLE_CLOCK_OP 0
#define LOOKUP_RAM_RAM_DDS1_AM_SIZE_MULTIPLE 1
#define LOOKUP_RAM_RAM_DDS1_AM_SIZE_VALUE 2048
#define LOOKUP_RAM_RAM_DDS1_AM_SPAN 2048
#define LOOKUP_RAM_RAM_DDS1_AM_TYPE "altera_avalon_onchip_memory2"
#define LOOKUP_RAM_RAM_DDS1_AM_WRITABLE 1


/*
 * LOOKUP_RAM_RAM_DDS1_FM configuration
 *
 */

#define ALT_MODULE_CLASS_LOOKUP_RAM_RAM_DDS1_FM altera_avalon_onchip_memory2
#define LOOKUP_RAM_RAM_DDS1_FM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define LOOKUP_RAM_RAM_DDS1_FM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define LOOKUP_RAM_RAM_DDS1_FM_BASE 0xb000
#define LOOKUP_RAM_RAM_DDS1_FM_CONTENTS_INFO ""
#define LOOKUP_RAM_RAM_DDS1_FM_DUAL_PORT 1
#define LOOKUP_RAM_RAM_DDS1_FM_GUI_RAM_BLOCK_TYPE "AUTO"
#define LOOKUP_RAM_RAM_DDS1_FM_INIT_CONTENTS_FILE "NiosII_Processor_LOOKUP_RAM_RAM_DDS1_FM"
#define LOOKUP_RAM_RAM_DDS1_FM_INIT_MEM_CONTENT 0
#define LOOKUP_RAM_RAM_DDS1_FM_INSTANCE_ID "NONE"
#define LOOKUP_RAM_RAM_DDS1_FM_IRQ -1
#define LOOKUP_RAM_RAM_DDS1_FM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LOOKUP_RAM_RAM_DDS1_FM_NAME "/dev/LOOKUP_RAM_RAM_DDS1_FM"
#define LOOKUP_RAM_RAM_DDS1_FM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define LOOKUP_RAM_RAM_DDS1_FM_RAM_BLOCK_TYPE "AUTO"
#define LOOKUP_RAM_RAM_DDS1_FM_READ_DURING_WRITE_MODE "DONT_CARE"
#define LOOKUP_RAM_RAM_DDS1_FM_SINGLE_CLOCK_OP 0
#define LOOKUP_RAM_RAM_DDS1_FM_SIZE_MULTIPLE 1
#define LOOKUP_RAM_RAM_DDS1_FM_SIZE_VALUE 2048
#define LOOKUP_RAM_RAM_DDS1_FM_SPAN 2048
#define LOOKUP_RAM_RAM_DDS1_FM_TYPE "altera_avalon_onchip_memory2"
#define LOOKUP_RAM_RAM_DDS1_FM_WRITABLE 1


/*
 * PIO_LED_DEBUG configuration
 *
 */

#define ALT_MODULE_CLASS_PIO_LED_DEBUG altera_avalon_pio
#define PIO_LED_DEBUG_BASE 0x89020
#define PIO_LED_DEBUG_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_LED_DEBUG_BIT_MODIFYING_OUTPUT_REGISTER 1
#define PIO_LED_DEBUG_CAPTURE 0
#define PIO_LED_DEBUG_DATA_WIDTH 1
#define PIO_LED_DEBUG_DO_TEST_BENCH_WIRING 0
#define PIO_LED_DEBUG_DRIVEN_SIM_VALUE 0
#define PIO_LED_DEBUG_EDGE_TYPE "NONE"
#define PIO_LED_DEBUG_FREQ 100000000
#define PIO_LED_DEBUG_HAS_IN 0
#define PIO_LED_DEBUG_HAS_OUT 1
#define PIO_LED_DEBUG_HAS_TRI 0
#define PIO_LED_DEBUG_IRQ -1
#define PIO_LED_DEBUG_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_LED_DEBUG_IRQ_TYPE "NONE"
#define PIO_LED_DEBUG_NAME "/dev/PIO_LED_DEBUG"
#define PIO_LED_DEBUG_RESET_VALUE 0
#define PIO_LED_DEBUG_SPAN 32
#define PIO_LED_DEBUG_TYPE "altera_avalon_pio"


/*
 * RAM_24K configuration
 *
 */

#define ALT_MODULE_CLASS_RAM_24K altera_avalon_onchip_memory2
#define RAM_24K_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define RAM_24K_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define RAM_24K_BASE 0x0
#define RAM_24K_CONTENTS_INFO ""
#define RAM_24K_DUAL_PORT 0
#define RAM_24K_GUI_RAM_BLOCK_TYPE "AUTO"
#define RAM_24K_INIT_CONTENTS_FILE "NiosII_Processor_RAM_24K"
#define RAM_24K_INIT_MEM_CONTENT 0
#define RAM_24K_INSTANCE_ID "NONE"
#define RAM_24K_IRQ -1
#define RAM_24K_IRQ_INTERRUPT_CONTROLLER_ID -1
#define RAM_24K_NAME "/dev/RAM_24K"
#define RAM_24K_NON_DEFAULT_INIT_FILE_ENABLED 0
#define RAM_24K_RAM_BLOCK_TYPE "AUTO"
#define RAM_24K_READ_DURING_WRITE_MODE "DONT_CARE"
#define RAM_24K_SINGLE_CLOCK_OP 0
#define RAM_24K_SIZE_MULTIPLE 1
#define RAM_24K_SIZE_VALUE 24000
#define RAM_24K_SPAN 24000
#define RAM_24K_TYPE "altera_avalon_onchip_memory2"
#define RAM_24K_WRITABLE 1


/*
 * RAM_24K configuration as viewed by LCD_DMA_read_master
 *
 */

#define LCD_DMA_READ_MASTER_RAM_24K_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define LCD_DMA_READ_MASTER_RAM_24K_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define LCD_DMA_READ_MASTER_RAM_24K_BASE 0x0
#define LCD_DMA_READ_MASTER_RAM_24K_CONTENTS_INFO ""
#define LCD_DMA_READ_MASTER_RAM_24K_DUAL_PORT 0
#define LCD_DMA_READ_MASTER_RAM_24K_GUI_RAM_BLOCK_TYPE "AUTO"
#define LCD_DMA_READ_MASTER_RAM_24K_INIT_CONTENTS_FILE "NiosII_Processor_RAM_24K"
#define LCD_DMA_READ_MASTER_RAM_24K_INIT_MEM_CONTENT 0
#define LCD_DMA_READ_MASTER_RAM_24K_INSTANCE_ID "NONE"
#define LCD_DMA_READ_MASTER_RAM_24K_IRQ -1
#define LCD_DMA_READ_MASTER_RAM_24K_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LCD_DMA_READ_MASTER_RAM_24K_NAME "/dev/RAM_24K"
#define LCD_DMA_READ_MASTER_RAM_24K_NON_DEFAULT_INIT_FILE_ENABLED 0
#define LCD_DMA_READ_MASTER_RAM_24K_RAM_BLOCK_TYPE "AUTO"
#define LCD_DMA_READ_MASTER_RAM_24K_READ_DURING_WRITE_MODE "DONT_CARE"
#define LCD_DMA_READ_MASTER_RAM_24K_SINGLE_CLOCK_OP 0
#define LCD_DMA_READ_MASTER_RAM_24K_SIZE_MULTIPLE 1
#define LCD_DMA_READ_MASTER_RAM_24K_SIZE_VALUE 24000
#define LCD_DMA_READ_MASTER_RAM_24K_SPAN 24000
#define LCD_DMA_READ_MASTER_RAM_24K_TYPE "altera_avalon_onchip_memory2"
#define LCD_DMA_READ_MASTER_RAM_24K_WRITABLE 1


/*
 * RAM_24K configuration as viewed by SPI_DMA_write_master
 *
 */

#define SPI_DMA_WRITE_MASTER_RAM_24K_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SPI_DMA_WRITE_MASTER_RAM_24K_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SPI_DMA_WRITE_MASTER_RAM_24K_BASE 0x0
#define SPI_DMA_WRITE_MASTER_RAM_24K_CONTENTS_INFO ""
#define SPI_DMA_WRITE_MASTER_RAM_24K_DUAL_PORT 0
#define SPI_DMA_WRITE_MASTER_RAM_24K_GUI_RAM_BLOCK_TYPE "AUTO"
#define SPI_DMA_WRITE_MASTER_RAM_24K_INIT_CONTENTS_FILE "NiosII_Processor_RAM_24K"
#define SPI_DMA_WRITE_MASTER_RAM_24K_INIT_MEM_CONTENT 0
#define SPI_DMA_WRITE_MASTER_RAM_24K_INSTANCE_ID "NONE"
#define SPI_DMA_WRITE_MASTER_RAM_24K_IRQ -1
#define SPI_DMA_WRITE_MASTER_RAM_24K_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SPI_DMA_WRITE_MASTER_RAM_24K_NAME "/dev/RAM_24K"
#define SPI_DMA_WRITE_MASTER_RAM_24K_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SPI_DMA_WRITE_MASTER_RAM_24K_RAM_BLOCK_TYPE "AUTO"
#define SPI_DMA_WRITE_MASTER_RAM_24K_READ_DURING_WRITE_MODE "DONT_CARE"
#define SPI_DMA_WRITE_MASTER_RAM_24K_SINGLE_CLOCK_OP 0
#define SPI_DMA_WRITE_MASTER_RAM_24K_SIZE_MULTIPLE 1
#define SPI_DMA_WRITE_MASTER_RAM_24K_SIZE_VALUE 24000
#define SPI_DMA_WRITE_MASTER_RAM_24K_SPAN 24000
#define SPI_DMA_WRITE_MASTER_RAM_24K_TYPE "altera_avalon_onchip_memory2"
#define SPI_DMA_WRITE_MASTER_RAM_24K_WRITABLE 1


/*
 * SD_SPI configuration
 *
 */

#define ALT_MODULE_CLASS_SD_SPI altera_avalon_spi
#define SD_SPI_BASE 0x8000
#define SD_SPI_CLOCKMULT 1
#define SD_SPI_CLOCKPHASE 0
#define SD_SPI_CLOCKPOLARITY 0
#define SD_SPI_CLOCKUNITS "Hz"
#define SD_SPI_DATABITS 8
#define SD_SPI_DATAWIDTH 16
#define SD_SPI_DELAYMULT "1.0E-9"
#define SD_SPI_DELAYUNITS "ns"
#define SD_SPI_EXTRADELAY 0
#define SD_SPI_INSERT_SYNC 0
#define SD_SPI_IRQ 6
#define SD_SPI_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SD_SPI_ISMASTER 1
#define SD_SPI_LSBFIRST 0
#define SD_SPI_NAME "/dev/SD_SPI"
#define SD_SPI_NUMSLAVES 1
#define SD_SPI_PREFIX "spi_"
#define SD_SPI_SPAN 32
#define SD_SPI_SYNC_REG_DEPTH 2
#define SD_SPI_TARGETCLOCK 10000000u
#define SD_SPI_TARGETSSDELAY "0.0"
#define SD_SPI_TYPE "altera_avalon_spi"


/*
 * SPI_DMA configuration
 *
 */

#define ALT_MODULE_CLASS_SPI_DMA altera_avalon_dma
#define SPI_DMA_ALLOW_BYTE_TRANSACTIONS 1
#define SPI_DMA_ALLOW_DOUBLEWORD_TRANSACTIONS 0
#define SPI_DMA_ALLOW_HW_TRANSACTIONS 0
#define SPI_DMA_ALLOW_QUADWORD_TRANSACTIONS 0
#define SPI_DMA_ALLOW_WORD_TRANSACTIONS 0
#define SPI_DMA_BASE 0x8020
#define SPI_DMA_IRQ 9
#define SPI_DMA_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SPI_DMA_LENGTHWIDTH 10
#define SPI_DMA_MAX_BURST_SIZE 128
#define SPI_DMA_NAME "/dev/SPI_DMA"
#define SPI_DMA_SPAN 32
#define SPI_DMA_TYPE "altera_avalon_dma"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "MAX 10"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/JTAG_UART"
#define ALT_STDERR_BASE 0x89088
#define ALT_STDERR_DEV JTAG_UART
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/JTAG_UART"
#define ALT_STDIN_BASE 0x89088
#define ALT_STDIN_DEV JTAG_UART
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/JTAG_UART"
#define ALT_STDOUT_BASE 0x89088
#define ALT_STDOUT_DEV JTAG_UART
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "NiosII_Processor"


/*
 * TIMER_DELAY_32bit configuration
 *
 */

#define ALT_MODULE_CLASS_TIMER_DELAY_32bit altera_avalon_timer
#define TIMER_DELAY_32BIT_ALWAYS_RUN 1
#define TIMER_DELAY_32BIT_BASE 0x89000
#define TIMER_DELAY_32BIT_COUNTER_SIZE 32
#define TIMER_DELAY_32BIT_FIXED_PERIOD 0
#define TIMER_DELAY_32BIT_FREQ 100000000
#define TIMER_DELAY_32BIT_IRQ 0
#define TIMER_DELAY_32BIT_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_DELAY_32BIT_LOAD_VALUE -2
#define TIMER_DELAY_32BIT_MULT 1.0E-8
#define TIMER_DELAY_32BIT_NAME "/dev/TIMER_DELAY_32bit"
#define TIMER_DELAY_32BIT_PERIOD 0xFFFFFFFF
#define TIMER_DELAY_32BIT_PERIOD_UNITS "clocks"
#define TIMER_DELAY_32BIT_RESET_OUTPUT 0
#define TIMER_DELAY_32BIT_SNAPSHOT 1
#define TIMER_DELAY_32BIT_SPAN 32
#define TIMER_DELAY_32BIT_TICKS_PER_SEC 0
#define TIMER_DELAY_32BIT_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_DELAY_32BIT_TYPE "altera_avalon_timer"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK TIMER_DELAY_32BIT
#define ALT_TIMESTAMP_CLK none

#endif /* __SYSTEM_H_ */
